version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - ./init_test_db.sql:/docker-entrypoint-initdb.d/init_test_db.sql
    ports:
      - ${PORT}:${PORT}
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://${USER}:${PASSWORD}@db:${PORT}/${DATABASE}
    ports:
      - "8000:8000"
    depends_on:
      - db